### ISSUE TITLE
Version 1.5.7 of the plugin breaks Pipeline support

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#789]
It appears that #747 inadvertently broke Pipeline support, and this was released today in version 1.5.7 of the plugin. 

`gitLabConnection` now throws a `java.lang.NoSuchMethodError: No such DSL method 'gitLabConnection' found` error, and `gitlabCommitStatus` throws `java.lang.IllegalArgumentException: Expected named arguments but got checkout`

@stchar please look into this ASAP.

All others, please downgrade to 1.5.6 if you encounter this issue.

**Comment by omehegan** [comment]
@stchar can you comment on this to confirm you're aware of it? If I don't hear anything today I will probably revert the PR and do another release so we don't have a broken version in the update center. Thanks!

**Comment by CelesteGH** [comment]
the gitlabCommitStatus signature has changed. it has nothing to do with the old version...
That's not a trivial impact.
Do downgrade indeed. 1.5.6 works with the latest version of gitlab (11.0.2)

**Comment by jandry** [comment]
Same issue for me. It's fixed after downgrade to 1.5.6

**Comment by IOOOTAlan** [comment]
Needed to downgrade to 1.5.6 too, because declarative pipeline jobs were not working anymore altogether.
I uploaded some more details on pastebin while asking for help on the IRC channel:
[Sample Jenkinsfile](https://pastebin.com/p7Up5xQq)
[Error stacktrace](https://pastebin.com/yYBD4YA6)

**Comment by ripper2hl** [comment]
Same problem :(

**Comment by omehegan** [comment]
I tested the fix in #793 locally, after first reproducing the problem in 1.5.7, and the fix seems to work. I published a snapshot with this fix at http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.5.8-SNAPSHOT/gitlab-plugin-1.5.8-20180703.040227-1.hpi I would recommend that other folks verify this before I merge and release it. Please comment here if you can confirm the problem is fixed.

**Comment by IOOOTAlan** [comment]
@omehegan I deployed the updated snapshot and confirm that declarative pipeline jobs run again with no changes on the Jenkinsfile used.
Will soon test if build status is correctly reported back to gitlab...

**Comment by rsommer** [comment]
@omehegan using the snapshot, all pipelines seem to run fine again without further changes. Commit status has been reported back to gitlab successfully.

**Comment by IOOOTAlan** [comment]
Ok, I can now confirm that the build status is successfully reported back to gitlab too.

**Comment by omehegan** [comment]
Released as 1.5.8.
